name: My Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  job8:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1"

  job2:
		needs: job8
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 2"
          