name: activity types

on:
  push: 
    branches: 
      [main, ashish]

jobs:
  jon1:
   runs-on: ubuntu-latest
   steps:
      - name: check test
        run: echo "${{github.actor}}"
   