name:  expression-context

on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print the username who triggered it
        run: echo "${{github.actor}}"
      - name: print the repositn name
        run: echo "${{github.repository}}"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: print the branhc
        run: echo "${{github.ref}}"
