name: testing the run runner number

on:
  push:
    branches:
      - main

jobs:
  first-deplay:
    runs-on: linux

    steps:
      - name:  first  test
        run: echo "Hello buddy"
        
      - name: tesing the steps
        run: |
          echo "Runner Name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Temp: $RUNNER_TEMP"
          echo "Workspace: $GITHUB_WORKSPACE"

      - name: Build
        run: |
          echo "Version: 1.0.${{ github.run_number }}"
      
          

