name: test the flow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "safas"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: bye
        run: echo "sfsa"
    