name: test the flow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "safas"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: bye
        run: echo "sfsa"

  job3:
    needs: [job1,job2]
    runs-on: ubuntu-latest
    steps:
      - name: running 3 job
        run: echo "running 3 job need to be aftewr  job2  onlu"

  job4:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name:  it's job 4 
        run:  echo "it time for the 4"
    