name: testing

on:
	pushes:
		branches:
			- main
			- workflow_dispatach


jobs:
	job1:
		runs-on: ubuntu-latest
			steps:
				- name: job 1
					run:  echo "first job say hello "

	job2:
		runs-on: ubuntu-latest
			steps:
				- name: job 2
					run: echo "seconf job say bye"